local colors = {
    -- content here will not be touched
    -- PATCH_OPEN
    Normal = { fg = '#EDE1D4', bg = '#12151C' },
    DiffText = { link = 'Normal' },
    FoldColumn = { link = 'Normal' },
    NormalNC = { link = 'Normal' },
    SignColumn = { link = 'Normal' },
    SpellBad = { link = 'Normal' },
    SpellCap = { link = 'Normal' },
    SpellLocal = { link = 'Normal' },
    SpellRare = { link = 'Normal' },
    Whitespace = { link = 'Normal' },
    ['@field'] = { link = 'Normal' },
    ['@property'] = { link = 'Normal' },
    CmpItemAbbrDeprecated = { fg = '#5A698C', strikethrough = true },
    CmpItemAbbrMatch = { fg = '#EEE3D7', bg = 'NONE' },
    CmpItemAbbrMatchFuzzy = { link = 'CmpItemAbbrMatch' },
    CmpItemKindClass = { fg = '#B8DBFF' },
    CmpItemKindEnum = { link = 'CmpItemKindClass' },
    CmpItemKindEvent = { link = 'CmpItemKindClass' },
    CmpItemKindStruct = { link = 'CmpItemKindClass' },
    CmpItemKindEnumMember = { link = 'CmpItemKindField' },
    CmpItemKindInterface = { link = 'CmpItemKindField' },
    CmpItemKindFunction = { fg = '#99CCFF' },
    CmpItemKindConstructor = { link = 'CmpItemKindFunction' },
    CmpItemKindMethod = { link = 'CmpItemKindFunction' },
    CmpItemKindKeyword = { fg = '#F4AD66' },
    CmpItemKindModule = { fg = '#E69393' },
    CmpItemKindProperty = { fg = '#B1D9AB' },
    CmpItemKindSnippet = { fg = '#4AC6D3' },
    CmpItemKindText = { fg = '#5FB253' },
    CmpItemKindColor = { link = 'CmpItemKindText' },
    CmpItemKindConstant = { link = 'CmpItemKindText' },
    CmpItemKindFile = { link = 'CmpItemKindText' },
    CmpItemKindFolder = { link = 'CmpItemKindText' },
    CmpItemKindOperator = { link = 'CmpItemKindText' },
    CmpItemKindReference = { link = 'CmpItemKindText' },
    CmpItemKindTypeParameter = { link = 'CmpItemKindText' },
    CmpItemKindUnit = { link = 'CmpItemKindText' },
    CmpItemKindValue = { link = 'CmpItemKindText' },
    CmpItemKindVariable = { fg = '#9595CB' },
    CmpItemKindField = { link = 'CmpItemKindVariable' },
    ColorColumn = { bg = '#1C212C' },
    Comment = { fg = '#63749C', italic = true },
    ['@comment'] = { link = 'Comment' },
    ['@text.literal'] = { link = 'Comment' },
    Conceal = {},
    Constant = { fg = '#4AC6D3' },
    Cursor = {},
    CursorColumn = {},
    CursorIM = {},
    CursorLine = { bg = '#1C212C' },
    CursorLineNr = { fg = '#E5A315', bold = true },
    DiagnosticError = { fg = '#CE3B3B', bg = '#1C212C' },
    DiagnosticUnderlineError = { link = 'DiagnosticError' },
    DiagnosticVirtualTextError = { link = 'DiagnosticError' },
    DiagnosticHint = { fg = '#FFDF9E', bg = '#1C212C' },
    DiagnosticVirtualTextHint = { link = 'DiagnosticHint' },
    DiagnosticInfo = { fg = '#CCE5FF', bg = '#1C212C' },
    DiagnosticVirtualTextInfo = { link = 'DiagnosticInfo' },
    DiagnosticOk = { fg = '#B1D9AB', bg = '#1C212C' },
    DiagnosticVirtualTextOk = { link = 'DiagnosticOk' },
    DiagnosticSignError = { fg = '#CE3B3B', bg = '#12151C' },
    DiagnosticFloatingError = { link = 'DiagnosticSignError' },
    DiagnosticSignHint = { fg = '#FFDF9E', bg = '#12151C' },
    DiagnosticFloatingHint = { link = 'DiagnosticSignHint' },
    DiagnosticSignInfo = { fg = '#CCE5FF', bg = '#12151C' },
    DiagnosticFloatingInfo = { link = 'DiagnosticSignInfo' },
    DiagnosticSignOk = { fg = '#B1D9AB', bg = '#12151C' },
    DiagnosticFloatingOk = { link = 'DiagnosticSignOk' },
    DiagnosticSignWarn = { fg = '#EFBF57', bg = '#12151C' },
    DiagnosticFloatingWarn = { link = 'DiagnosticSignWarn' },
    DiagnosticWarn = { fg = '#EFBF57', bg = '#1C212C' },
    DiagnosticVirtualTextWarn = { link = 'DiagnosticWarn' },
    DiffAdd = { fg = '#A0D199', bg = '#12151C' },
    DiffChange = { fg = '#C2E0FF', bg = '#12151C' },
    DiffDelete = { fg = '#CE3B3B', bg = '#12151C' },
    Directory = { fg = '#A3D1FF', bold = true },
    EndOfBuffer = { fg = '#12151C' },
    ErrorMsg = { fg = '#D86464' },
    FloatBorder = {},
    FloatTitle = {},
    CursorLineFold = { link = 'FoldColumn' },
    Folded = {},
    Function = { fg = '#B1D9AB', bold = true },
    ['@method'] = { link = 'Function' },
    IblIndent = { fg = '#242A38' },
    IblScope = { fg = '#7F8DAD' },
    IblWhitespace = { fg = '#525F80' },
    Identifier = { fg = '#EDE1D4' },
    Keyword = { fg = '#F4AD66', bold = true },
    LineNr = { fg = '#E5A315', bg = '#12151C', bold = true },
    LineNrAbove = { fg = '#485470', bg = '#12151C' },
    LineNrBelow = { fg = '#485470', bg = '#12151C' },
    LspCodeLens = {},
    LspCodeLensSeparator = {},
    LspReferenceRead = {},
    LspReferenceText = {},
    LspReferenceWrite = {},
    LspSignatureActiveParameter = {},
    MatchParen = { fg = '#E5A315', bg = '#485470' },
    ModeMsg = {},
    MoreMsg = {},
    MsgArea = { fg = '#EDE1D4', bg = '#12151C' },
    MsgSeparator = {},
    NonText = {},
    NormalFloat = { fg = '#4AC6D3', bg = '#12151C' },
    Pmenu = { fg = '#8F9BB7', bg = '#1E232F' },
    PmenuExtra = { fg = '#4AC6D3' },
    PmenuExtraSel = { fg = '#4AC6D3', bg = '#4AC6D3' },
    PmenuKind = { bg = '#4AC6D3' },
    PmenuKindSel = { fg = '#4AC6D3' },
    PmenuSbar = { bg = '#363F54' },
    PmenuSel = { fg = '#EDE1D4', bg = '#6565B3' },
    PmenuThumb = { bg = '#5A698C' },
    PreProc = { fg = '#B1D9AB' },
    Question = {},
    QuickFixLine = {},
    Search = { fg = '#12151C', bg = '#ADD6FF' },
    CurSearch = { link = 'Search' },
    IncSearch = { link = 'Search' },
    Substitute = { link = 'Search' },
    CursorLineSign = { link = 'SignColumn' },
    Special = { fg = '#E5A315' },
    SpecialKey = { fg = '#363F54' },
    Statement = { fg = '#E5A315' },
    StatusLine = { bg = '#1A1E28' },
    StatusLineNC = { bg = '#12151C' },
    String = { fg = '#74BE8A' },
    TabLine = {},
    TabLineFill = {},
    TabLineSel = {},
    TelescopeBorder = { fg = '#171A1C', bg = '#171A1C' },
    TelescopePreviewBorder = { link = 'TelescopeBorder' },
    TelescopeResultsBorder = { link = 'TelescopeBorder' },
    TelescopeMatching = { fg = '#E5A315' },
    TelescopeMultiIcon = { fg = '#99CCFF' },
    TelescopeNormal = { fg = '#EDE1D4', bg = '#171A1C' },
    TelescopePreviewTitle = { fg = '#12151C', bg = '#B1D9AB' },
    TelescopePromptBorder = { fg = '#101313', bg = '#101313' },
    TelescopePromptNormal = { bg = '#101313' },
    TelescopePromptPrefix = { fg = '#B1D9AB' },
    TelescopePromptTitle = { fg = '#12151C', bg = '#B1D9AB' },
    TelescopeResultsTitle = { fg = '#12151C', bg = '#B1D9AB' },
    TelescopeSelection = { fg = '#EDE1D4', bg = '#101313' },
    TelescopeSelectionCaret = { link = 'TelescopeSelection' },
    TermCursor = { fg = '#12151C', bg = '#EDE1D4' },
    TermCursorNC = { fg = '#12151C', bg = '#12151C' },
    Title = { fg = '#B1D9AB', bold = true },
    Type = { fg = '#9595CB' },
    Underlined = { underline = true },
    VertSplit = { fg = '#E5A315' },
    Visual = { bg = '#242A38' },
    VisualNOS = { link = 'Visual' },
    WarningMsg = { fg = '#FFDF9E' },
    WildMenu = {},
    WinBar = {},
    WinBarNC = {},
    Winseparator = { fg = '#242A38' },
    diffAdded = { fg = '#5FB253' },
    diffLine = { fg = '#485470', bold = true },
    diffRemoved = { fg = '#D35050' },
    diffSubname = { fg = '#EFBF57', bold = true },
    fugitiveHash = { fg = '#B1D9AB' },
    fugitiveHeader = { fg = '#CF8E6E' },
    fugitiveHeading = { fg = '#99CCFF', bold = true },
    fugitiveHelpTag = { fg = '#9595CB' },
    fugitiveSection = { fg = '#F8FCF8' },
    fugitiveStagedHeading = { fg = '#99CCFF', bold = true },
    fugitiveStagedModifier = { fg = '#B1D9AB', bold = true },
    fugitiveUnStagedModifier = { link = 'fugitiveStagedModifier' },
    fugitiveUntrackedModifier = { link = 'fugitiveStagedModifier' },
    fugitiveStagedSection = { fg = '#F8FCF8' },
    fugitiveSymbolicRef = { fg = '#C2E0FF' },
    fugitiveUnStagedHeading = { fg = '#99CCFF', bold = true },
    fugitiveUnTrackedHeading = { fg = '#99CCFF', bold = true },
    fugitiveUnstagedSection = { fg = '#F8FCF8' },
    lCursor = {},
    ['@boolean.typescript'] = { fg = '#2CA9FC' },
    ['@boolean.yaml'] = { fg = '#4AC6D3', bold = true },
    ['@character'] = { fg = '#E5A315' },
    ['@character.special'] = { fg = '#4AC6D3' },
    ['@constant'] = { fg = '#4AC6D3' },
    ['@function'] = { fg = '#99CCFF' },
    ['@function.call'] = { fg = '#99CCFF' },
    ['@function.builtin'] = { link = '@function.call' },
    ['@function.method.call.python'] = { link = '@function.call' },
    ['@function.macro'] = {},
    ['@keyword'] = { fg = '#F4AD66', bold = true },
    ['@keyword.gitcommit'] = { fg = '#99CCFF', bold = true },
    ['@type.qualifier.java'] = { link = '@keyword' },
    ['@type.qualifier.typescript'] = { link = '@keyword' },
    ['@label'] = { fg = '#4AC6D3' },
    ['@lsp.type.class.typescript'] = { fg = '#2CA9FC' },
    ['@markup.heading.1.markdown'] = { fg = '#99CCFF', bold = true },
    ['@markup.heading.2.markdown'] = { fg = '#B1D9AB', bold = true },
    ['@markup.heading.3.markdown'] = { fg = '#95568E', bold = true },
    ['@markup.heading.4.markdown'] = { fg = '#784572', bold = true },
    ['@markup.heading.gitcommit'] = { fg = '#B1D9AB', bold = true },
    ['@markup.italic.markdown_inline'] = { fg = '#B884B2', italic = true },
    asciidocQuotedEmphasizedItalic = { link = '@markup.italic.markdown_inline' },
    ['@markup.link.label.markdown_inline'] = { fg = '#ADD6FF' },
    ['@markup.link.markdown_inline'] = { fg = '#ADD6FF' },
    ['@markup.link.url.markdown_inline'] = { fg = '#FFD480' },
    ['@markup.list.markdown'] = { fg = '#4AC6D3', bold = true },
    ['@markup.quote.markdown'] = { fg = '#F3C9C9', bold = true },
    ['@markup.raw.block.markdown'] = { fg = '#9595CB' },
    ['@markup.raw.markdown_inline'] = { fg = '#5FB253' },
    asciidocQuotedMonospaced2 = { link = '@markup.raw.markdown_inline' },
    ['@markup.strong.markdown_inline'] = { fg = '#F2C86E', bold = true },
    asciidocQuotedBold = { link = '@markup.strong.markdown_inline' },
    ['@number'] = { fg = '#E69393' },
    ['@boolean'] = { link = '@number' },
    ['@float'] = { link = '@number' },
    ['@operator'] = { fg = '#EDE1D4' },
    ['@parameter'] = { fg = '#9595CB' },
    ['@property.yaml'] = { fg = '#99CCFF' },
    ['@punctuation'] = { fg = '#E69393' },
    ['@punctuation.bracket.yaml'] = { fg = '#E5A315', bold = true },
    ['@punctuation.special.markdown'] = { fg = '#4AC6D3' },
    ['@string'] = { fg = '#74BE8A' },
    ['@string.escape'] = { fg = '#BADEC5' },
    ['@string.special'] = { link = '@string.escape' },
    ['@string.special.url.gitcommit'] = { fg = '#EDE1D4' },
    ['@string.yaml'] = { fg = '#74BE8A' },
    ['@text.todo'] = { fg = '#4AC6D3', bg = '#363F54', bold = true },
    ['@type'] = { fg = '#2CA9FC', bold = true },
    ['@type.builtin'] = { fg = '#9595CB', bold = true },
    ['@type.yaml'] = { fg = '#FFCA61', bold = true },
    ['@constructor'] = { link = '@type' },
    ['@variable'] = { fg = '#EDE1D4' },
    ['@variable.builtin'] = { fg = '#C397BE' },
    ['@variable.parameter'] = { fg = '#D9C0A5' },
    ['@lsp.type.parameter.typescript'] = { link = '@variable' },
    ['@lsp.type.property.typescript'] = { link = '@variable' },
    ['@lsp.type.variable.typescript'] = { link = '@variable' },
    ['@type.typescript'] = { link = '@variable' },
    -- PATCH_CLOSE
    -- content here will not be touched
}

vim.cmd('highlight clear')
vim.cmd('set t_Co=256')
vim.cmd("let g:colors_name='okai'")

for group, attrs in pairs(colors) do
    vim.api.nvim_set_hl(0, group, attrs)
end
